/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.input-data[_ngcontent-%COMP%] {\n  display: flex;\n  flex-direction: column;\n}\n.input-data[_ngcontent-%COMP%]   .block[_ngcontent-%COMP%] {\n  position: relative;\n  padding: 20px 10px;\n}\n.input-data[_ngcontent-%COMP%]   .block[_ngcontent-%COMP%]   .add[_ngcontent-%COMP%] {\n  position: absolute;\n  right: 10px;\n  top: 40px;\n  font-size: 50px;\n  visibility: hidden;\n  cursor: pointer;\n}\n.input-data[_ngcontent-%COMP%]   .block[_ngcontent-%COMP%]:hover   .add[_ngcontent-%COMP%] {\n  visibility: visible;\n}'];