/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
/* tslint:disable */
"use strict";
exports.styles = ['.toolbar[_ngcontent-%COMP%] {\n  display: flex;\n  position: relative;\n  height: 50px;\n  background-color: #eee;\n  box-shadow: 0 1px 5px #333;\n  z-index: 100;\n}\n.toolbar__run[_ngcontent-%COMP%] {\n  cursor: pointer;\n  font-size: 25px;\n  padding: 10px;\n}\n.toolbar__run[_ngcontent-%COMP%]:hover {\n  background-color: #333;\n  color: #eee;\n}\n.body[_ngcontent-%COMP%] {\n  position: relative;\n  display: flex;\n  flex: 1;\n  z-index: 99;\n}\n.body[_ngcontent-%COMP%]   .side-panel[_ngcontent-%COMP%] {\n  display: none;\n  flex: 1;\n  z-index: 98;\n  background: #369;\n  box-shadow: 1px 0 5px #333;\n}\n.body[_ngcontent-%COMP%]   .side-panel__title[_ngcontent-%COMP%] {\n  display: inline-block;\n  padding: 5px;\n  text-transform: uppercase;\n  width: 100%;\n  text-align: center;\n  background: #333;\n  color: #eee;\n}\n.body[_ngcontent-%COMP%]   .center[_ngcontent-%COMP%] {\n  display: flex;\n  flex: 3;\n  background-color: #fff;\n  z-index: 97;\n}\n.body[_ngcontent-%COMP%]   .center[_ngcontent-%COMP%]   .blocks[_ngcontent-%COMP%] {\n  display: flex;\n  flex-direction: column;\n  padding: 50px 0;\n}\n.body[_ngcontent-%COMP%]   .active[_ngcontent-%COMP%] {\n  display: block;\n}\n.flex-1[_ngcontent-%COMP%] {\n  flex: 1;\n}'];
//# sourceMappingURL=code-blocks-list.css.shim.js.map