/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../../app/alsu/code-blocks-lists/code-blocks-list/code-blocks-list.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './code-blocks-list.css.shim';
import * as import9 from '../../../../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import10 from '../../../../../app/alsu/code-blocks-lists/code-blocks-list/input/input-data.component';
import * as import11 from './input/input-data.component.ngfactory';
import * as import12 from '@angular/core/src/linker/view_container';
import * as import13 from '../../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import14 from '../../../../../app/alsu/code-blocks-lists/code-blocks-list/output/output-data.component';
import * as import15 from './output/output-data.component.ngfactory';
import * as import16 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import17 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import18 from '@angular/core/src/linker/element_ref';
import * as import19 from '@angular/core/src/linker/template_ref';
import * as import20 from '@angular/common/src/directives/ng_class';
import * as import21 from '@angular/common/src/directives/ng_for';
import * as import22 from '../../../../../app/alsu/code-blocks-lists/code-blocks-list/code-block/code-block.component';
import * as import23 from './code-block/code-block.component.ngfactory';
export class Wrapper_CodeBlocksListComponent {
  /*private*/ _eventHandler:Function;
  context:import0.CodeBlocksListComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.CodeBlocksListComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_CodeBlocksListComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_CodeBlocksListComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.CodeBlocksListComponent>;
  _CodeBlocksListComponent_0_3:Wrapper_CodeBlocksListComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_CodeBlocksListComponent_Host0,renderType_CodeBlocksListComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'code-blocks-list',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_CodeBlocksListComponent0(this.viewUtils,this,0,this._el_0);
    this._CodeBlocksListComponent_0_3 = new Wrapper_CodeBlocksListComponent();
    this.compView_0.create(this._CodeBlocksListComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._CodeBlocksListComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.CodeBlocksListComponent) && (0 === requestNodeIndex))) { return this._CodeBlocksListComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._CodeBlocksListComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const CodeBlocksListComponentNgFactory:import7.ComponentFactory<import0.CodeBlocksListComponent> = new import7.ComponentFactory<import0.CodeBlocksListComponent>('code-blocks-list',View_CodeBlocksListComponent_Host0,import0.CodeBlocksListComponent);
const styles_CodeBlocksListComponent:any[] = [import8.styles];
var renderType_CodeBlocksListComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_CodeBlocksListComponent,{});
export class View_CodeBlocksListComponent0 extends import1.AppView<import0.CodeBlocksListComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _NgClass_12_3:import9.Wrapper_NgClass;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  compView_17:import1.AppView<import10.InputDataComponent>;
  _InputDataComponent_17_3:import11.Wrapper_InputDataComponent;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _anchor_28:any;
  /*private*/ _vc_28:import12.ViewContainer;
  _TemplateRef_28_5:any;
  _NgFor_28_6:import13.Wrapper_NgFor;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _NgClass_34_3:import9.Wrapper_NgClass;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  compView_39:import1.AppView<import14.OutputDataComponent>;
  _OutputDataComponent_39_3:import15.Wrapper_OutputDataComponent;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  /*private*/ _expr_52:any;
  _map_53:any;
  _map_54:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_CodeBlocksListComponent0,renderType_CodeBlocksListComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_52 = import6.UNINITIALIZED;
    this._map_53 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {active: p0};
    });
    this._map_54 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {active: p0};
    });
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','toolbar'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','flex-1'),(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_0,'i',new import3.InlineArray2(2,'class','toolbar__run material-icons'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','flex-1'),(null as any));
    this._text_8 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','body'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n\n  ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_10,'div',new import3.InlineArray2(2,'class','side-panel'),(null as any));
    this._NgClass_12_3 = new import9.Wrapper_NgClass(this.parentView.injectorGet(import16.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import17.KeyValueDiffers,this.parentIndex),new import18.ElementRef(this._el_12),this.renderer);
    this._text_13 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_12,'span',new import3.InlineArray2(2,'class','side-panel__title'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'input',(null as any));
    this._text_16 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_12,'input-data',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_17 = new import11.View_InputDataComponent0(this.viewUtils,this,17,this._el_17);
    this._InputDataComponent_17_3 = new import11.Wrapper_InputDataComponent();
    this.compView_17.create(this._InputDataComponent_17_3.context);
    this._text_18 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_12,'div',new import3.InlineArray2(2,'class','add'),(null as any));
    this._text_20 = this.renderer.createText(this._el_12,'\n  ',(null as any));
    this._text_21 = this.renderer.createText(this._el_10,'\n\n    ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_10,'div',new import3.InlineArray2(2,'class','center'),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_22,'div',new import3.InlineArray2(2,'class','flex-1'),(null as any));
    this._text_25 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_22,'div',new import3.InlineArray2(2,'class','blocks'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'\n\n        ',(null as any));
    this._anchor_28 = this.renderer.createTemplateAnchor(this._el_26,(null as any));
    this._vc_28 = new import12.ViewContainer(28,26,this,this._anchor_28);
    this._TemplateRef_28_5 = new import19.TemplateRef_(this,28,this._anchor_28);
    this._NgFor_28_6 = new import13.Wrapper_NgFor(this._vc_28.vcRef,this._TemplateRef_28_5,this.parentView.injectorGet(import16.IterableDiffers,this.parentIndex),this.ref);
    this._text_29 = this.renderer.createText(this._el_26,'\n\n      ',(null as any));
    this._text_30 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_22,'div',new import3.InlineArray2(2,'class','flex-1'),(null as any));
    this._text_32 = this.renderer.createText(this._el_22,'\n    ',(null as any));
    this._text_33 = this.renderer.createText(this._el_10,'\n\n  ',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_10,'div',new import3.InlineArray2(2,'class','side-panel'),(null as any));
    this._NgClass_34_3 = new import9.Wrapper_NgClass(this.parentView.injectorGet(import16.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import17.KeyValueDiffers,this.parentIndex),new import18.ElementRef(this._el_34),this.renderer);
    this._text_35 = this.renderer.createText(this._el_34,'\n    ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_34,'span',new import3.InlineArray2(2,'class','side-panel__title'),(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'output',(null as any));
    this._text_38 = this.renderer.createText(this._el_34,'\n    ',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_34,'output-data',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_39 = new import15.View_OutputDataComponent0(this.viewUtils,this,39,this._el_39);
    this._OutputDataComponent_39_3 = new import15.Wrapper_OutputDataComponent();
    this.compView_39.create(this._OutputDataComponent_39_3.context);
    this._text_40 = this.renderer.createText(this._el_34,'\n  ',(null as any));
    this._text_41 = this.renderer.createText(this._el_10,'\n\n',(null as any));
    this._text_42 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_4,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_4));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_17,new import3.InlineArray2(2,'add',(null as any)),this.eventHandler(this.handleEvent_17));
    this._InputDataComponent_17_3.subscribe(this,this.eventHandler(this.handleEvent_17),true);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._anchor_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._text_42
    ]
    ),[
      disposable_0,
      disposable_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.InputDataComponent) && (17 === requestNodeIndex))) { return this._InputDataComponent_17_3.context; }
    if (((token === import20.NgClass) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._NgClass_12_3.context; }
    if (((token === import19.TemplateRef) && (28 === requestNodeIndex))) { return this._TemplateRef_28_5; }
    if (((token === import21.NgFor) && (28 === requestNodeIndex))) { return this._NgFor_28_6.context; }
    if (((token === import14.OutputDataComponent) && (39 === requestNodeIndex))) { return this._OutputDataComponent_39_3.context; }
    if (((token === import20.NgClass) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._NgClass_34_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_12_0_0:any = 'side-panel';
    this._NgClass_12_3.check_klass(currVal_12_0_0,throwOnChange,false);
    const currVal_12_0_1:any = this._map_53(this.context.editMode.enabled);
    this._NgClass_12_3.check_ngClass(currVal_12_0_1,throwOnChange,false);
    this._NgClass_12_3.ngDoCheck(this,this._el_12,throwOnChange);
    this._InputDataComponent_17_3.ngDoCheck(this,this._el_17,throwOnChange);
    const currVal_28_0_0:any = this.context.list.blocks;
    this._NgFor_28_6.check_ngForOf(currVal_28_0_0,throwOnChange,false);
    this._NgFor_28_6.ngDoCheck(this,this._anchor_28,throwOnChange);
    const currVal_34_0_0:any = 'side-panel';
    this._NgClass_34_3.check_klass(currVal_34_0_0,throwOnChange,false);
    const currVal_34_0_1:any = this._map_54(!this.context.editMode.enabled);
    this._NgClass_34_3.check_ngClass(currVal_34_0_1,throwOnChange,false);
    this._NgClass_34_3.ngDoCheck(this,this._el_34,throwOnChange);
    const currVal_39_0_0:any = this.context.outputData;
    this._OutputDataComponent_39_3.check_outputData(currVal_39_0_0,throwOnChange,false);
    this._OutputDataComponent_39_3.ngDoCheck(this,this._el_39,throwOnChange);
    this._vc_28.detectChangesInNestedViews(throwOnChange);
    const currVal_52:any = import3.inlineInterpolate(1,'',this.context.editMode.run,'');
    if (import3.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this.renderer.setText(this._text_5,currVal_52);
      this._expr_52 = currVal_52;
    }
    this.compView_17.detectChanges(throwOnChange);
    this.compView_39.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_28.destroyNestedViews();
    this.compView_17.destroy();
    this.compView_39.destroy();
    this._InputDataComponent_17_3.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 28)) { return new View_CodeBlocksListComponent1(this.viewUtils,this,28,this._anchor_28,this._vc_28); }
    return (null as any);
  }
  handleEvent_4(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.run()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_17(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'add')) {
      const pd_sub_0:any = ((<any>this.context.add($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_CodeBlocksListComponent1 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import22.CodeBlockComponent>;
  _CodeBlockComponent_0_3:import23.Wrapper_CodeBlockComponent;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import12.ViewContainer) {
    super(View_CodeBlocksListComponent1,renderType_CodeBlocksListComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'code-block',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import23.View_CodeBlockComponent0(this.viewUtils,this,0,this._el_0);
    this._CodeBlockComponent_0_3 = new import23.Wrapper_CodeBlockComponent();
    this._text_1 = this.renderer.createText((null as any),'\n        ',(null as any));
    this.compView_0.create(this._CodeBlockComponent_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray4(4,'click',(null as any),'remove',(null as any)),this.eventHandler(this.handleEvent_0));
    this._CodeBlockComponent_0_3.subscribe(this,this.eventHandler(this.handleEvent_0),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.CodeBlockComponent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._CodeBlockComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.$implicit;
    this._CodeBlockComponent_0_3.check_block(currVal_0_0_0,throwOnChange,false);
    const currVal_0_0_1:any = this.parentView.context.list.selectedId;
    this._CodeBlockComponent_0_3.check_selectedId(currVal_0_0_1,throwOnChange,false);
    this._CodeBlockComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._CodeBlockComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.list.selectId(this.context.$implicit.id)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'remove')) {
      const pd_sub_1:any = ((<any>this.parentView.context.remove()) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
}