/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../app/alsu/code-blocks/code-blocks.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from './code-blocks.css.shim';
import * as import9 from '@angular/core/src/linker/view_container';
import * as import10 from '../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import11 from '../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import12 from '../../../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import13 from '@angular/core/src/linker/template_ref';
import * as import14 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import15 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import16 from '@angular/core/src/linker/element_ref';
import * as import17 from '@angular/common/src/directives/ng_if';
import * as import18 from '@angular/common/src/directives/ng_for';
import * as import19 from '@angular/common/src/directives/ng_class';
import * as import20 from '../../../../app/alsu/code-blocks/input/input.component';
import * as import21 from './input/input.component.ngfactory';
import * as import22 from '../../../../app/alsu/code-blocks/block/block.component';
import * as import23 from './block/block.component.ngfactory';
import * as import24 from '../../../../app/alsu/code-blocks/output/output.component';
import * as import25 from './output/output.component.ngfactory';
export class Wrapper_CodeBlocksComponent {
  /*private*/ _eventHandler:Function;
  context:import0.CodeBlocksComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.CodeBlocksComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_CodeBlocksComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_CodeBlocksComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.CodeBlocksComponent>;
  _CodeBlocksComponent_0_3:Wrapper_CodeBlocksComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_CodeBlocksComponent_Host0,renderType_CodeBlocksComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'code-blocks',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_CodeBlocksComponent0(this.viewUtils,this,0,this._el_0);
    this._CodeBlocksComponent_0_3 = new Wrapper_CodeBlocksComponent();
    this.compView_0.create(this._CodeBlocksComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._CodeBlocksComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.CodeBlocksComponent) && (0 === requestNodeIndex))) { return this._CodeBlocksComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._CodeBlocksComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const CodeBlocksComponentNgFactory:import7.ComponentFactory<import0.CodeBlocksComponent> = new import7.ComponentFactory<import0.CodeBlocksComponent>('code-blocks',View_CodeBlocksComponent_Host0,import0.CodeBlocksComponent);
const styles_CodeBlocksComponent:any[] = [import8.styles];
var renderType_CodeBlocksComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_CodeBlocksComponent,{});
export class View_CodeBlocksComponent0 extends import1.AppView<import0.CodeBlocksComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _anchor_13:any;
  /*private*/ _vc_13:import9.ViewContainer;
  _TemplateRef_13_5:any;
  _NgIf_13_6:import10.Wrapper_NgIf;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _anchor_21:any;
  /*private*/ _vc_21:import9.ViewContainer;
  _TemplateRef_21_5:any;
  _NgFor_21_6:import11.Wrapper_NgFor;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _NgClass_26_3:import12.Wrapper_NgClass;
  _text_27:any;
  _text_28:any;
  _anchor_29:any;
  /*private*/ _vc_29:import9.ViewContainer;
  _TemplateRef_29_5:any;
  _NgIf_29_6:import10.Wrapper_NgIf;
  _text_30:any;
  _text_31:any;
  /*private*/ _expr_42:any;
  _map_43:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_CodeBlocksComponent0,renderType_CodeBlocksComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_42 = import6.UNINITIALIZED;
    this._map_43 = import3.pureProxy1((p0:any):{[key: string]:any} => {
      return {_disabled: p0};
    });
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','toolbar'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_1,'div',new import3.InlineArray2(2,'class','flex'),(null as any));
    this._text_4 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_1,'i',new import3.InlineArray2(2,'class','toolbar__run material-icons'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_1,'div',new import3.InlineArray2(2,'class','flex'),(null as any));
    this._text_9 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._text_10 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_11 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','body'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'\n\n    ',(null as any));
    this._anchor_13 = this.renderer.createTemplateAnchor(this._el_11,(null as any));
    this._vc_13 = new import9.ViewContainer(13,11,this,this._anchor_13);
    this._TemplateRef_13_5 = new import13.TemplateRef_(this,13,this._anchor_13);
    this._NgIf_13_6 = new import10.Wrapper_NgIf(this._vc_13.vcRef,this._TemplateRef_13_5);
    this._text_14 = this.renderer.createText(this._el_11,'\n\n    ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,this._el_11,'div',new import3.InlineArray2(2,'class','code-blocks'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_15,'div',new import3.InlineArray2(2,'class','flex'),(null as any));
    this._text_18 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_15,'div',new import3.InlineArray2(2,'class','code-blocks__wrapper'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'\n\n            ',(null as any));
    this._anchor_21 = this.renderer.createTemplateAnchor(this._el_19,(null as any));
    this._vc_21 = new import9.ViewContainer(21,19,this,this._anchor_21);
    this._TemplateRef_21_5 = new import13.TemplateRef_(this,21,this._anchor_21);
    this._NgFor_21_6 = new import11.Wrapper_NgFor(this._vc_21.vcRef,this._TemplateRef_21_5,this.parentView.injectorGet(import14.IterableDiffers,this.parentIndex),this.ref);
    this._text_22 = this.renderer.createText(this._el_19,'\n\n        ',(null as any));
    this._text_23 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_15,'div',new import3.InlineArray2(2,'class','flex'),(null as any));
    this._text_25 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_15,'div',new import3.InlineArray2(2,'class','code-blocks__backdrop'),(null as any));
    this._NgClass_26_3 = new import12.Wrapper_NgClass(this.parentView.injectorGet(import14.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import15.KeyValueDiffers,this.parentIndex),new import16.ElementRef(this._el_26),this.renderer);
    this._text_27 = this.renderer.createText(this._el_15,'\n\n    ',(null as any));
    this._text_28 = this.renderer.createText(this._el_11,'\n\n    ',(null as any));
    this._anchor_29 = this.renderer.createTemplateAnchor(this._el_11,(null as any));
    this._vc_29 = new import9.ViewContainer(29,11,this,this._anchor_29);
    this._TemplateRef_29_5 = new import13.TemplateRef_(this,29,this._anchor_29);
    this._NgIf_29_6 = new import10.Wrapper_NgIf(this._vc_29.vcRef,this._TemplateRef_29_5);
    this._text_30 = this.renderer.createText(this._el_11,'\n\n',(null as any));
    this._text_31 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_5,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_5));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._anchor_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._anchor_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._anchor_29,
      this._text_30,
      this._text_31
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.TemplateRef) && (13 === requestNodeIndex))) { return this._TemplateRef_13_5; }
    if (((token === import17.NgIf) && (13 === requestNodeIndex))) { return this._NgIf_13_6.context; }
    if (((token === import13.TemplateRef) && (21 === requestNodeIndex))) { return this._TemplateRef_21_5; }
    if (((token === import18.NgFor) && (21 === requestNodeIndex))) { return this._NgFor_21_6.context; }
    if (((token === import19.NgClass) && (26 === requestNodeIndex))) { return this._NgClass_26_3.context; }
    if (((token === import13.TemplateRef) && (29 === requestNodeIndex))) { return this._TemplateRef_29_5; }
    if (((token === import17.NgIf) && (29 === requestNodeIndex))) { return this._NgIf_29_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_13_0_0:any = this.context.editMode.enabled;
    this._NgIf_13_6.check_ngIf(currVal_13_0_0,throwOnChange,false);
    this._NgIf_13_6.ngDoCheck(this,this._anchor_13,throwOnChange);
    const currVal_21_0_0:any = this.context.list.blocks;
    this._NgFor_21_6.check_ngForOf(currVal_21_0_0,throwOnChange,false);
    this._NgFor_21_6.ngDoCheck(this,this._anchor_21,throwOnChange);
    const currVal_26_0_0:any = 'code-blocks__backdrop';
    this._NgClass_26_3.check_klass(currVal_26_0_0,throwOnChange,false);
    const currVal_26_0_1:any = this._map_43(!this.context.editMode.enabled);
    this._NgClass_26_3.check_ngClass(currVal_26_0_1,throwOnChange,false);
    this._NgClass_26_3.ngDoCheck(this,this._el_26,throwOnChange);
    const currVal_29_0_0:boolean = !this.context.editMode.enabled;
    this._NgIf_29_6.check_ngIf(currVal_29_0_0,throwOnChange,false);
    this._NgIf_29_6.ngDoCheck(this,this._anchor_29,throwOnChange);
    this._vc_13.detectChangesInNestedViews(throwOnChange);
    this._vc_21.detectChangesInNestedViews(throwOnChange);
    this._vc_29.detectChangesInNestedViews(throwOnChange);
    const currVal_42:any = import3.inlineInterpolate(1,'',this.context.editMode.toolbarIcon,'\n    ');
    if (import3.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this.renderer.setText(this._text_6,currVal_42);
      this._expr_42 = currVal_42;
    }
  }
  destroyInternal():void {
    this._vc_13.destroyNestedViews();
    this._vc_21.destroyNestedViews();
    this._vc_29.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 13)) { return new View_CodeBlocksComponent1(this.viewUtils,this,13,this._anchor_13,this._vc_13); }
    if ((nodeIndex == 21)) { return new View_CodeBlocksComponent2(this.viewUtils,this,21,this._anchor_21,this._vc_21); }
    if ((nodeIndex == 29)) { return new View_CodeBlocksComponent3(this.viewUtils,this,29,this._anchor_29,this._vc_29); }
    return (null as any);
  }
  handleEvent_5(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.compile()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_CodeBlocksComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  compView_5:import1.AppView<import20.InputComponent>;
  _InputComponent_5_3:import21.Wrapper_InputComponent;
  _text_6:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_CodeBlocksComponent1,renderType_CodeBlocksComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','side-panel'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'span',new import3.InlineArray2(2,'class','side-panel__title'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'input',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'input-data',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_5 = new import21.View_InputComponent0(this.viewUtils,this,5,this._el_5);
    this._InputComponent_5_3 = new import21.Wrapper_InputComponent();
    this.compView_5.create(this._InputComponent_5_3.context);
    this._text_6 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_5,new import3.InlineArray2(2,'add',(null as any)),this.eventHandler(this.handleEvent_5));
    this._InputComponent_5_3.subscribe(this,this.eventHandler(this.handleEvent_5),true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.InputComponent) && (5 === requestNodeIndex))) { return this._InputComponent_5_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._InputComponent_5_3.ngDoCheck(this,this._el_5,throwOnChange);
    this.compView_5.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_5.destroy();
    this._InputComponent_5_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_5(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'add')) {
      const pd_sub_0:any = ((<any>this.parentView.context.add($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_CodeBlocksComponent2 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import22.BlockComponent>;
  _BlockComponent_0_3:import23.Wrapper_BlockComponent;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_CodeBlocksComponent2,renderType_CodeBlocksComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'block',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import23.View_BlockComponent0(this.viewUtils,this,0,this._el_0);
    this._BlockComponent_0_3 = new import23.Wrapper_BlockComponent();
    this._text_1 = this.renderer.createText((null as any),'\n            ',(null as any));
    this.compView_0.create(this._BlockComponent_0_3.context);
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray8(6,'select',(null as any),'move',(null as any),'remove',(null as any)),this.eventHandler(this.handleEvent_0));
    this._BlockComponent_0_3.subscribe(this,this.eventHandler(this.handleEvent_0),true,true,true);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.BlockComponent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._BlockComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.$implicit;
    this._BlockComponent_0_3.check_block(currVal_0_0_0,throwOnChange,false);
    this._BlockComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._BlockComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'select')) {
      const pd_sub_0:any = ((<any>this.parentView.context.select($event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'move')) {
      const pd_sub_1:any = ((<any>this.parentView.context.move($event)) !== false);
      result = (pd_sub_1 && result);
    }
    if ((eventName == 'remove')) {
      const pd_sub_2:any = ((<any>this.parentView.context.remove()) !== false);
      result = (pd_sub_2 && result);
    }
    return result;
  }
}
class View_CodeBlocksComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  compView_5:import1.AppView<import24.OutputComponent>;
  _OutputComponent_5_3:import25.Wrapper_OutputComponent;
  _text_6:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_CodeBlocksComponent3,renderType_CodeBlocksComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','side-panel'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'span',new import3.InlineArray2(2,'class','side-panel__title'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'output',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'output-data',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_5 = new import25.View_OutputComponent0(this.viewUtils,this,5,this._el_5);
    this._OutputComponent_5_3 = new import25.Wrapper_OutputComponent();
    this.compView_5.create(this._OutputComponent_5_3.context);
    this._text_6 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.OutputComponent) && (5 === requestNodeIndex))) { return this._OutputComponent_5_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_5_0_0:any = this.parentView.context.editMode.output;
    this._OutputComponent_5_3.check_outputData(currVal_5_0_0,throwOnChange,false);
    this._OutputComponent_5_3.ngDoCheck(this,this._el_5,throwOnChange);
    this.compView_5.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_5.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}