/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.toolbar[_ngcontent-%COMP%] {\n  position: relative;\n  height: 50px;\n  padding: 15px;\n  background-color: #eee;\n  box-shadow: 0 1px 5px #333;\n  z-index: 100;\n}\n.body[_ngcontent-%COMP%] {\n  position: relative;\n  display: flex;\n  flex: 1;\n  z-index: 99;\n}\n.body[_ngcontent-%COMP%]   .left-side[_ngcontent-%COMP%] {\n  flex: 1;\n  box-shadow: 1px 0 5px #333;\n  z-index: 98;\n  background: #369;\n}\n.body[_ngcontent-%COMP%]   .center[_ngcontent-%COMP%] {\n  flex: 3;\n  background-color: #fff;\n  z-index: 97;\n}\n.body[_ngcontent-%COMP%]   .right-side[_ngcontent-%COMP%] {\n  flex: 1;\n  z-index: 98;\n  background: #369;\n}'];