/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.input-data[_ngcontent-%COMP%] {\n  display: flex;\n  flex-direction: column;\n}\n.input-data[_ngcontent-%COMP%]   .block[_ngcontent-%COMP%] {\n  display: flex;\n  position: relative;\n  padding: 10px;\n}\n.input-data[_ngcontent-%COMP%]   .block[_ngcontent-%COMP%]    > div[_ngcontent-%COMP%] {\n  flex: 1;\n  cursor: pointer;\n}\n.input-data[_ngcontent-%COMP%]   .block[_ngcontent-%COMP%]   .add[_ngcontent-%COMP%] {\n  position: relative;\n  float: left;\n  top: 30px;\n  left: 5px;\n  font-size: 30px;\n  visibility: hidden;\n  color: #333;\n}\n.input-data[_ngcontent-%COMP%]   .block[_ngcontent-%COMP%]:hover   .add[_ngcontent-%COMP%] {\n  visibility: visible;\n}\n[_nghost-%COMP%]     block .block-connection {\n  visibility: hidden;\n}\n[_nghost-%COMP%]     block .block {\n  border: 2px solid #333;\n}'];