/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.output-data[_ngcontent-%COMP%] {\n  display: flex;\n  flex-direction: column;\n  cursor: pointer;\n}\n.output-data__row[_ngcontent-%COMP%] {\n  padding: 10px 20px;\n  font-size: 40px;\n}'];